#version 430 core
    layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
    layout(std430, binding = 0) buffer InBuffer { int gridIn[]; };
    layout(std430, binding = 1) buffer OutBuffer { int gridOut[]; };
    uniform int uSize;
    int getIdx(ivec3 p) {
        return p.x + p.y * uSize + p.z * uSize * uSize;
    }
    void main() {
        ivec3 pos = ivec3(gl_GlobalInvocationID.xyz);
        if (pos.x >= uSize || pos.y >= uSize || pos.z >= uSize) return;
        int neighbors = 0;
        for(int x = -1; x <= 1; x++) {
            for(int y = -1; y <= 1; y++) {
                for(int z = -1; z <= 1; z++) {
                    if(x == 0 && y == 0 && z == 0) continue;\
                    ivec3 nPos = pos + ivec3(x, y, z);
                    if(nPos.x >= 0 && nPos.x < uSize && nPos.y >= 0 && nPos.y < uSize && nPos.z >= 0 && nPos.z < uSize) {
                        if(gridIn[getIdx(nPos)] == 1) neighbors++;
                    }
                }
            }
        }
        int current = gridIn[getIdx(pos)];
        int next = 0;
        if(current == 1 && neighbors >= 5 && neighbors <= 8) next = 1;
        else if(current == 0 && neighbors == 6) next = 1;
        gridOut[getIdx(pos)] = next;
    }